services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: 'pg_isready --username=postgres'
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
